# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1bbbcdb70e52a948bdce0cfa02b8077880ea708d40e3144b7c356c26393f78edb90b8fcd5a14fa68503a92e118110705111f90fb709babfb7b05bec6b62afb3

test:
  secret_key_base: 82d72742f2e4c4553e6f045b489e4bc727a9064eb1950b3c3ba8db8f378419ccbc8ea538bf69145e9fbe0b7afd9f52fe00e343abbe25ae8767d992a7325b82db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
